In [ ]:
# 10.1



In [38]:
# 10.2
# 1)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5,5)

print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [13]:
# 2)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5,5)

fitst= n_arr[0,0]
print('첫 원소 :' , fitst)

last = n_arr[-1,-1]
print('마지막 원소 :', last)

첫 원소 : 0
마지막 원소 : 24


In [39]:
# 3)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5,5)

result = n_arr[0:2]

print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
# 4)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5,5)

result = n_arr[2:5]

print(result)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
# 5)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5,5)

result = n_arr[:, ::2]

print(result)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [29]:
# 6)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5,5)

result = n_arr[::2, ::2]

print(result)

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


In [45]:
# 7)
import numpy as np

a = np.arange(25)
n_arr = a.reshape(5, 5)

result = n_arr[:5, :2]

print(result)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


In [41]:
# 10.3
# 1)
import numpy as np

a = np.random.random((3,3,3))

print(a)

[[[0.1188761  0.29622488 0.69997893]
  [0.42025782 0.29304461 0.93522721]
  [0.60933196 0.96402775 0.56401526]]

 [[0.18488038 0.98540236 0.92096573]
  [0.69350588 0.08657434 0.6423674 ]
  [0.50465062 0.15614111 0.33543408]]

 [[0.45728678 0.68525979 0.36989662]
  [0.9201324  0.20546272 0.27926044]
  [0.75965397 0.06395965 0.56764795]]]


In [42]:
# 2)
print('a의 원소들 중 최대값 :',np.max(a))

a의 원소들 중 최대값 : 0.9854023552257889


In [43]:
# 3)
print('a의 원소들 중 최대값의 위치 :',np.argmax(a))

a의 원소들 중 최대값의 위치 : 10


In [57]:
# 10.4
# 1)
import numpy as np

matrix = np.zeros((5, 5), dtype=int)

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [59]:
# 2)

result = matrix.sum(axis=1)

print("행렬의 행 방향 성분의 합 : ")
print(result)

행렬의 행 방향 성분의 합 : 
[3 2 3 2 3]


In [65]:
# 10.5
import numpy as np

a = np.arange(0, 32)
n_arr = a.reshape(4, 4, 2)

result1 = n_arr.flatten()[9]
result2 = n_arr.flatten()[19]

print("10번째 원소 : ", result1)
print("20번째 원소 : ", result2)

10번째 원소 :  9
20번째 원소 :  19


In [95]:
# 10.6
# 1)
import numpy as np

x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1, 10) for i in range(100)]
x3 = [i + np.random.randint(1, 50) for i in range(100)]
x4 = [np.random.randint(1, 100) for i in range(100)]

x1 = np.array(x1)
x2 = np.array(x2)
x3 = np.array(x3)
x4 = np.array(x4)

corr_x1_x2 = np.corrcoef(x1, x2)[0, 1]
corr_x1_x3 = np.corrcoef(x1, x3)[0, 1]
corr_x1_x4 = np.corrcoef(x1, x4)[0, 1]

max_corr = max(corr_x1_x2, corr_x1_x3, corr_x1_x4)

most_correlated_lists = []
if max_corr == corr_x1_x2:
    most_correlated_lists.append("x2")
if max_corr == corr_x1_x3:
    most_correlated_lists.append("x3")
if max_corr == corr_x1_x4:
    most_correlated_lists.append("x4")

print(f"x1과 가장 상관관계가 높은 리스트는? : {', '.join(most_correlated_lists)}")

x1과 가장 상관관계가 높은 리스트: x2


In [96]:
import numpy as np

x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1, 10) for i in range(100)]
x3 = [i + np.random.randint(1, 50) for i in range(100)]
x4 = [np.random.randint(1, 100) for i in range(100)]

x1 = np.array(x1)
x2 = np.array(x2)
x3 = np.array(x3)
x4 = np.array(x4)

corr_x1_x2 = np.corrcoef(x1, x2)[0, 1]
corr_x1_x3 = np.corrcoef(x1, x3)[0, 1]
corr_x1_x4 = np.corrcoef(x1, x4)[0, 1]

min_corr = min(corr_x1_x2, corr_x1_x3, corr_x1_x4)

least_correlated_lists = []
if min_corr == corr_x1_x2:
    least_correlated_lists.append("x2")
if min_corr == corr_x1_x3:
    least_correlated_lists.append("x3")
if min_corr == corr_x1_x4:
    least_correlated_lists.append("x4")

print(f"x1과 가장 상관관계가 낮은 리스트는? : {', '.join(least_correlated_lists)}")

x1과 가장 상관관계가 낮은 리스트는? : x4
